# Generated by Django 3.2.9 on 2021-12-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=2083)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.courses')),
            ],
        ),
    ]
